name: "Release a tag"
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: copy with version in name
        run: cp ./bin/tool-versions-to-env ./tool-versions-to-env-${{ github.ref }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .tool-versions-to-env-${{ github.ref }}
            LICENSE
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}